server:
  port: 8082
  servlet:
    context-path: /wechat
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wechat
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.wechat.demo.domain
  mapper-locations: classpath:mappingxml/*.xml